spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: embedded
    job:
      enabled: false

  quartz:
    jdbc:
      initialize-schema: embedded
    job-store-type: jdbc



logging.level:
  org.hibernate.SQL: debug